@include('common.head.head')
<body>
@yield('header')
@yield('content')
@yield('service')
@yield('portfolio')
@yield('clients')
@yield('team')
@include('common.footer.footer')
@include('js')
</body>
</html>
